using System;
using System.Collections.Generic;

namespace ModelsDTOLayer
{
    public class ApiHome
    {
        public int HomeId { get; set; }
        public int ListingId { get; set; }
        public string ListingTitle { get; set; }
        public string ListingNumber { get; set; }
        public bool IsSpec { get; set; }
        public int PlanId { get; set; }
        public string PlanName { get; set; }
        public string SpecNum { get; set; }
        public string Desc { get; set; }
        public int IsDescAutoGenerated { get; set; }
        public string MoveInDate { get; set; }
        public string MarketingDesc { get; set; }
        public string Addr { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public int Br { get; set; }
        public int BrLo { get; set; }
        public int BrHi { get; set; }
        public int MasterBedroomLocation { get; set; }
        public int Ba { get; set; }
        public int BaLo { get; set; }
        public int BaHi { get; set; }
        public bool DisplayAddress { get; set; }
        public int FeedProviderId { get; set; }
        public int HBa { get; set; }
        public int HBaLo { get; set; }
        public int HBaHi { get; set; }
        public decimal St { get; set; }
        public decimal StLo { get; set; }
        public decimal StHi { get; set; }
        public decimal Gr { get; set; }
        public decimal GrLo { get; set; }
        public decimal GrHi { get; set; }
        public int Sft { get; set; }
        public int SftLo { get; set; }
        public int SftHi { get; set; }
        public int LotSft { get; set; }
        public string LotNumber { get; set; }
        public decimal Price { get; set; }
        public decimal PriceLo { get; set; }
        public decimal PriceHi { get; set; }
        public decimal ModelPrice { get; set; }
        public string ProviderUrl { get; set; }
        public int NumLivingAreas { get; set; }
        public string Status { get; set; }
        public int IsHotHome { get; set; }
        public string Thumb { get; set; }
        public string Phone { get; set; }
        public string PhoneTracking { get; set; }
        public bool IsTrackingNumber { get; set; }
        public int MktId { get; set; }
        public string MarketName { get; set; }
        public string MarketStateAbbr { get; set; }
        public string MarketStateName { get; set; }
        public string MlsNumber { get; set; }
        public int MlsProviderId { get; set; }
        public int CommId { get; set; }
        public string CommName { get; set; }
        public int ParentCommId { get; set; }
        public string ParentCommName { get; set; }
        public bool IsParentCommActive { get; set; }
        public string CommListingTypeFlag { get; set; }
        public string CommType { get; set; }
        public string CommProjectType { get; set; }
        public string CommDesc { get; set; }
        public string CommunityUrl { get; set; }
        public string CommAddr { get; set; }
        public string CommAddr2 { get; set; }
        public string CommCity { get; set; }
        public string CommState { get; set; }
        public string CommZip { get; set; }
        public decimal CommLat { get; set; }
        public decimal CommLng { get; set; }
        public string CommBannerImage { get; set; }
        public decimal CommPriceLow { get; set; }
        public decimal CommPriceHigh { get; set; }
        public bool IsBasic { get; set; }
        public string SchoolDistricts { get; set; }
        public decimal Lat { get; set; }
        public decimal Lng { get; set; }
        public string PlanTypeId { get; set; }
        public string PlanBrandName { get; set; }
        public string PlanBrandLogo { get; set; }
        public Builder Builder { get; set; }
        public Brand Brand { get; set; }
        public IEnumerable<ApiImage> Images { get; set; }
        public IEnumerable<ApiImage> PlanImages { get; set; }
        public IEnumerable<ApiVideo> Videos { get; set; }
        public IEnumerable<ApiSummary> Summaries { get; set; }
        public IEnumerable<ApiSummary> PlanAmenities { get; set; }
        public IEnumerable<ApiSummary> LivingAreas { get; set; }
        public IEnumerable<ApiInteractiveMedia> IntMedia { get; set; }
        public IEnumerable<ApiCustomAmenity> CustomAmenities { get; set; }
        public IEnumerable<ApiHomeOption> HomeOptions { get; set; }
        public IList<ApiSchoolDistrict> Schools { get; set; }
        public List<ApiAmenity> Amenities { get; set; }
        public List<ApiUtility> Utilities { get; set; }
        public IEnumerable<ApiSalesAgent> Agents { get; set; }
        public IEnumerable<ApiBrochure> Brochures { get; set; }
        public IEnumerable<BookmarkAttribute> Bookmarks { get; set; }
        public List<ApiFeesAndRates> FeesAndRates { get; set; }
        public List<ApiUrgencyResponse> UrgencyData { get; set; }
        /*public ApiHome()
        {
            Images = new List<ApiImage>();
            PlanImages = new List<ApiImage>();
            Videos = new List<ApiVideo>();
            Summaries = new List<ApiSummary>();
            PlanAmenities = new List<ApiSummary>();
            LivingAreas = new List<ApiSummary>();
            IntMedia = new List<ApiInteractiveMedia>();
            CustomAmenities = new List<ApiCustomAmenity>();
            HomeOptions = new List<ApiHomeOption>();
        }*/
    }

}
